version: '3.8'

services:
  wuog-scraper:
    build: .
    # image: ghcr.io/nkirchoff/wuog-docker:latest
    container_name: wuog_scraper
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    ports:
      - "1785:1785" # Web server to view CSVs
    environment:
      - TZ=America/New_York
